application: kpachecker
version: 1
runtime: go
api_version: go1

handlers:
- url: /media
  static_dir: media

- url: /check
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required